#!/usr/bin/env bash

set -e
root="$( cd $(dirname $0)/.. && pwd)"

promise_name="$(basename "$(dirname "${root}")")"

wcrbin=${root}/scripts/worker-resource-builder

if [ ! -f $wcrbin ]; then
  echo "please download the worker-resource-builder binary and place it in the scripts directory"
  exit 1
fi

if [ ! -d "${root}/resources" ]; then
  exit 0
fi

promise_contents=$(${wcrbin} \
  -k8s-resources-directory "${root}/resources" \
  -promise "${root}/../promise.yaml")

echo "$promise_contents" > "${root}/../promise.yaml"
