#!/usr/bin/env bash

set -e

PWD="$( cd $(dirname $0)/.. && pwd)"


if [ -z $PIPELINE_NAME ]; then
  echo "\$PIPELINE_NAME is not set"
  exit 1
fi

echo "Image: $PIPELINE_NAME"
while [ $# -gt 0 ]; do
  case "$1" in
    build)
      docker build \
        --tag "${PIPELINE_NAME}" \
        --platform linux/amd64 \
        "${PWD}/request-pipeline" ;;

    load)
      kind load docker-image "${PIPELINE_NAME}" --name platform ;;

    push)
      docker push "${PIPELINE_NAME}" ;;

    rmi)
      docker rmi --force "${PIPELINE_NAME}" ;;

    pull)
      docker pull "${PIPELINE_NAME}" ;;

    *)
      echo "unknown command $1"
      exit 1
      ;;
  esac
  shift
done
